// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGQxQhqYsF5I622Oa6ywVxvis9nQ7mDmQ',
    appId: '1:1015990778323:web:60c66a15bc81bbfeb65726',
    messagingSenderId: '1015990778323',
    projectId: 'pdbl-project-d61da',
    authDomain: 'pdbl-project-d61da.firebaseapp.com',
    storageBucket: 'pdbl-project-d61da.firebasestorage.app',
    measurementId: 'G-W3T4QH2KGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIoB7BTYQ1MXkIp3un75O2wiZ-9NWJ9ts',
    appId: '1:1015990778323:android:e2236eaa465a013ab65726',
    messagingSenderId: '1015990778323',
    projectId: 'pdbl-project-d61da',
    storageBucket: 'pdbl-project-d61da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvllTLCiOjJRefB9j-OQyXjAD9Hf66OQg',
    appId: '1:1015990778323:ios:c532ff72f1f025d6b65726',
    messagingSenderId: '1015990778323',
    projectId: 'pdbl-project-d61da',
    storageBucket: 'pdbl-project-d61da.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvllTLCiOjJRefB9j-OQyXjAD9Hf66OQg',
    appId: '1:1015990778323:ios:c532ff72f1f025d6b65726',
    messagingSenderId: '1015990778323',
    projectId: 'pdbl-project-d61da',
    storageBucket: 'pdbl-project-d61da.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGQxQhqYsF5I622Oa6ywVxvis9nQ7mDmQ',
    appId: '1:1015990778323:web:72e7a23530453b4db65726',
    messagingSenderId: '1015990778323',
    projectId: 'pdbl-project-d61da',
    authDomain: 'pdbl-project-d61da.firebaseapp.com',
    storageBucket: 'pdbl-project-d61da.firebasestorage.app',
    measurementId: 'G-XFDBEXRVZN',
  );
}
